TOSIT-IO/tdp-ui

scripts/downloadGenerator.sh
=> chore: conditionally download jar file

src/contexts/TdpClientContext.tsx
=> fix: initialize context as null

.github/PULL_REQUEST_TEMPLATE.md
=> 21 update pr template

.gitignore, README.md, docs/openapi-client.md, env/.env.dev, env/export/docker-compose.yml, env/export/templates/default.conf.template, package-lock.json, package.json, src/clients/TdpClient.ts, src/config/api.ts, src/config/index.ts, src/contexts/AuthContextProvider.tsx, src/contexts/index.ts, src/pages/_app.tsx, src/pages/login.tsx
=> 17 authentication

src/components/Tableau.tsx
=> fix: boolean display value

src/components/ComponentInfos.tsx, src/components/Tableau.tsx, src/hooks/index.ts, src/hooks/useComponentInfos.ts, src/pages/services/[serviceId].tsx
=> feat: display component variables

src/app/LoginPortal.tsx, src/app/dashboard/Sidebar.tsx, src/clients/axiosClient.tsx, src/clients/index.ts, src/clients/tdpClient.tsx, src/config/index.ts, src/contexts/AuthContextProvider.tsx, src/contexts/TdpClientContext.tsx, src/hooks/useServicesList.ts, src/pages/_app.tsx
Fixes #27 
Memoize `tdpClient` instance to avoid fetching from 0 on each new page.
=> 27 enable authentication for services

src/contexts/AuthContextProvider.tsx, src/pages/services/[serviceId].tsx
=> fix: serviceId matching services components

package-lock.json, package.json, src/app/dashboard/layout.tsx, src/clients/axiosClient.tsx
=> feat: intercept axios errors

package-lock.json, package.json, src/app/dashboard/Menu.tsx, src/app/dashboard/Sidebar.tsx, src/app/deploy/InputField.tsx, src/app/deploy/Operation.tsx, src/app/deploy/OperationsContext.tsx, src/app/deploy/OperationsList.tsx, src/components/Button.tsx, src/hooks/useDeploy.ts, src/pages/deploy/index.tsx, src/utils/index.ts
=> 52 deploy page

src/app/dashboard/Menu.tsx, src/app/dashboard/Sidebar.tsx
Fixes none
Prevent the sidebar to overflow when window height is too small.
=> fix: sidebar overflow

scripts/generator.sh
=> fix: fix generation condition

schemas/tdp-server_0.1.0_openapi.json, src/config/index.ts
=> chore: update server schema

src/app/dashboard/Menu.tsx
=> fix: 404 on /services

src/components/Services/VariablesDisplay/index.tsx, src/hooks/useComponentInfos.ts, src/hooks/useServiceInfos.ts, src/types/index.ts
=> feat: variable change res on toast

README.md, env/compose.yml
=> feat: build from tdp-server's github

src/clients/tdpClient.tsx, src/components/Deploy/3-ReviewStep/ReviewStep.tsx, src/hooks/useDeploy.ts
=> feat: preview step

src/app/LoginPortal.tsx, src/config/index.ts, src/contexts/AuthContextProvider.tsx
=> feat: logout redirection

src/components/Services/ComponentsNav/ComponentsDropdown.tsx, src/components/Services/ComponentsNav/ComponentsNav.tsx, src/components/Services/ComponentsNav/ComponentsTabs.tsx, src/components/Services/ComponentsNav/hooks/useComponentsList.ts, src/components/Services/ComponentsNav/type.ts
=> feat: hide unused component tabs

src/components/Deploy/DeployLogs/DeployLogs.tsx, src/components/Deploy/DeployLogs/DeploysInfos.tsx, src/components/Deploy/DeployLogs/OperationsList.tsx, src/utils/dateAndTime.ts, src/utils/index.ts
=> feat: adding hour in the date format

src/utils/index.ts
=> fix: remove getUser export

src/components/Login/Login.tsx, src/components/Login/LoginPortal.tsx, src/contexts/AuthContextProvider.tsx
=> feat: resume navigation when login

src/components/Deploy/DeployLogs/DeployLogs.tsx, src/components/Deploy/DeployLogs/OperationsList.tsx
=> fix: handle no endTime case

src/app/dashboard/deploy/layout.tsx, src/components/Layout/Menu.tsx, src/contexts/AuthContextProvider.tsx, src/pages/deploy/index.tsx, src/pages/deploy/new/dag.tsx, src/pages/deploy/new/index.tsx, src/pages/deploy/new/operations.tsx, src/pages/deploy/new/reconfigure.tsx
Move the new/deploy page from the menu to the main deploy page.
Fixes #106
=> feat: merge deploy pages

src/pages/deploy/index.tsx
=> feat: no board when no past deploy log

src/components/Services/ParamsContext.tsx, src/hooks/usePutServiceConfig.ts
=> feat: refresh variables when switching service

src/components/Layout/Layout.tsx
=> fix: remove bottom margin

src/components/Deploy/DeployLogs/DetailLogView.tsx, src/components/Deploy/DeployLogs/OperationsList.tsx, src/components/Deploy/DeployLogs/index.tsx, src/hooks/index.ts, src/hooks/useDeploymentOperation.ts, src/utils/dateAndTime.ts
Fixes #123 
You can access the deployment log of an operation by clicking on the "View" button of an operation deployment.
=> feat: 123-past-deployment-text-logs

src/hooks/usePutServiceConfig.tsx
Fixes #141 
I had to rename the file to .tsx to add code in the toast.
The style of the toast may (will) be done in another issue.
=> feat: redirection after variable edition ; commit after rebase master

README.md, package.json
=> feat: rename postinstall script

scripts/generator.sh
=> refactor: improve generate script

schemas/tdp-server_0.1.0_openapi.json, src/components/Deploy/DeployDag/hooks/useDagDeploy.ts, src/components/Deploy/DeployOperations/hooks/useDeployOperations.ts, src/components/Services/VariablesDisplay/ValidateBar.tsx, src/pages/deploy/new/reconfigure.tsx
=> feat: create missing toasts

package-lock.json, src/components/Deploy/DeployDag/hooks/useDagDeploy.ts, src/components/Deploy/DeployOperations/hooks/useDeployOperations.ts, src/pages/deploy/new/reconfigure.tsx
Fixes #184 
There's a problem in the redirection : the OPTIONS request is hanging, due to the launch of the task with tdp-server.
=> feat: redirection after a deployment launch
